# Generated by Django 2.1.2 on 2018-11-07 21:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('modelno', models.CharField(max_length=50)),
                ('condition', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinLengthValidator(1)])),
                ('price', models.FloatField()),
                ('buy', models.DateField()),
            ],
        ),
    ]
