# Generated by Django 2.1.2 on 2018-11-07 21:56

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mobile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='buy',
            field=models.DateField(default=datetime.date(2018, 11, 8)),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='condition',
            field=models.PositiveSmallIntegerField(max_length=25, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='price',
            field=models.FloatField(max_length=20),
        ),
    ]
